// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Clock, Coffee } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="About Us"
          title="Industrial Style, Relaxed Atmosphere"
          description="Cafe Hrnek is a discreet neighborhood gem. We serve more than just great coffee; we provide a space to slow down and enjoy the small moments in a curated, industrial-inspired setting."
          items={[
            {
              icon: Coffee,
              title: "Specialty Coffee",
              description: "Professional brewing techniques featuring flat whites and artisanal roasts.",
            },
            {
              icon: Coffee,
              title: "Homemade Food",
              description: "Fresh cinnamon pastries, mozzarella toast, and seasonal breakfast options.",
            },
            {
              icon: Clock,
              title: "Relaxed Vibe",
              description: "The perfect spot for your morning ritual or an afternoon of slow work.",
            },
          ]}
          imageSrc="https://images.pexels.com/photos/4790053/pexels-photo-4790053.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"
        />
        </SectionErrorBoundary>
      </div>
  );
}
