// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visit Us"
          text="Open daily until 6pm. Visit us at Veletržní 839/49, Praha 7-Holešovice."
          primaryButton={{
            text: "Get Directions",
            href: "https://maps.app.goo.gl/4bZL24RM8KhbPvDWA",
          }}
          secondaryButton={{
            text: "Call +420 608 672 661",
            href: "tel:+420608672661",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
