// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesArrowCards
          tag="Our Highlights"
          title="More Than a Cafe"
          description="Discover why our guests return time and time again."
          items={[
            {
              title: "Artisan Coffee Culture",
              tags: [
                "Specialty",
                "Fresh",
              ],
              imageSrc: "https://images.pexels.com/photos/30444143/pexels-photo-30444143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Gourmet Breakfasts",
              tags: [
                "Healthy",
                "Freshly Made",
              ],
              imageSrc: "https://images.pexels.com/photos/7071232/pexels-photo-7071232.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Industrial Atmosphere",
              tags: [
                "Relaxing",
                "Cool Vibe",
              ],
              imageSrc: "https://images.pexels.com/photos/29205832/pexels-photo-29205832.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
