// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlay from '@/components/sections/hero/HeroOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroOverlay
          tag="Veletržní 839/49, Praha 7"
          title="Your Neighborhood Specialty Coffee Spot"
          description="Experience industrial charm, artisan pastries, and professional coffee in the heart of Prague 7-Holešovice."
          primaryButton={{
            text: "View Menu",
            href: "#menu",
          }}
          secondaryButton={{
            text: "Directions",
            href: "#contact",
          }}
          imageSrc="https://images.pexels.com/photos/31358912/pexels-photo-31358912.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"
        />
        </SectionErrorBoundary>
      </div>
  );
}
