// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
        <SectionErrorBoundary name="menu">
              <FeaturesImageBento
          tag="Popular Menu Items"
          title="Curated Treats"
          description="From perfect flat whites to our signature cinnamon buns."
          items={[
            {
              title: "Cinnamon Roll",
              description: "Warm, soft, and perfectly spiced.",
              imageSrc: "https://images.pexels.com/photos/9949102/pexels-photo-9949102.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Flat White",
              description: "Professionally prepared specialty coffee.",
              imageSrc: "https://images.pexels.com/photos/4671862/pexels-photo-4671862.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Scrambled Eggs",
              description: "On homemade bread with fresh spread.",
              imageSrc: "https://images.pexels.com/photos/27554108/pexels-photo-27554108.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Mozzarella Toast",
              description: "Crispy, fresh, and accurate.",
              imageSrc: "https://images.pexels.com/photos/15512508/pexels-photo-15512508.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Granola Bowl",
              description: "Seasonal yogurt with house granola.",
              imageSrc: "https://images.pexels.com/photos/19933488/pexels-photo-19933488.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Cappuccino",
              description: "Classic Italian style coffee.",
              imageSrc: "https://images.pexels.com/photos/31875562/pexels-photo-31875562.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
            {
              title: "Banana Bread",
              description: "A favorite neighborhood classic.",
              imageSrc: "https://images.pexels.com/photos/32106689/pexels-photo-32106689.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
