/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Star } from "lucide-react";
import { cls } from "@/lib/utils";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const testimonials = [
  {
    name: "C S P",
    role: "Local Guide",
    company: "Regular",
    rating: 5,
    quote: "We came across this café while exploring the area, and it really lived up to the reviews. It’s quite discreet from the street, but once inside it’s a lovely space — industrial in style, cool and relaxed, with a great atmosphere.",
    imageSrc: "https://images.pexels.com/photos/33421713/pexels-photo-33421713.png?auto=compress&cs=tinysrgb&h=650&w=940"
  },
  {
    name: "Verena Geiregger",
    role: "Local Guide",
    company: "Traveler",
    rating: 5,
    quote: "We almost would have walked past it, as it is quite inconspicuous from the outside. But inside it is a very nice, cozy café with a great atmosphere. The coffee was excellent and the cinnamon bun was also very tasty.",
    imageSrc: "https://images.pexels.com/photos/9210490/pexels-photo-9210490.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"
  },
  {
    name: "Sagit Tohar",
    role: "Local Guide",
    company: "Visitor",
    rating: 5,
    quote: "A very nice cafe, with a pleasant atmosphere, excellent coffee and delicious pastries. The service is very kind and welcoming. Highly recommended!",
    imageSrc: "https://images.pexels.com/photos/36342215/pexels-photo-36342215.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"
  },
  {
    name: "Kamal Rosode",
    role: "Customer",
    company: "Neighborhood",
    rating: 5,
    quote: "Great coffee, great atmosphere, great service. The cinnamon bun was amazing. Highly recommended!",
    imageSrc: "https://images.pexels.com/photos/8936935/pexels-photo-8936935.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"
  },
  {
    name: "Konstantin Kandaurov",
    role: "Visitor",
    company: "Prague 7",
    rating: 5,
    quote: "Excellent specialty coffee and a great place to work or relax. The staff is super friendly and the interior is beautiful.",
    imageSrc: "https://images.pexels.com/photos/29291840/pexels-photo-29291840.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"
  }
];

type Testimonial = {
  name: string;
  role: string;
  company: string;
  rating: number;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TestimonialsInline = () => {
  const duplicated = [...testimonials, ...testimonials, ...testimonials, ...testimonials];

  return (
    <section aria-label="Testimonials section" className="pt-20 pb-10">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"What Guests Say"}</p>
          </div>

          <TextAnimation
            text={"Loved by the Neighborhood"}
            variant="fade-blur"
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Join 770+ reviewers who rated us 4.7/5 stars."}
            variant="fade-blur"
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="slide-up">
          <div className="w-content-width mx-auto overflow-hidden mask-fade-x-medium">
            <div className="flex w-max animate-marquee-horizontal" style={{ animationDuration: "60s" }}>
              {duplicated.map((testimonial, i) => (
                <div key={i} className="group relative shrink-0 w-60 md:w-75 2xl:w-80 aspect-4/5 mb-10 mr-3 md:mr-5 [perspective:1000px]">
                  <div className="relative w-full h-full transition-transform duration-700 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
                    {/* Front */}
                    <div className="absolute inset-0 [backface-visibility:hidden] rounded overflow-hidden">
                      <ImageOrVideo
                        imageSrc={testimonial.imageSrc}
                        videoSrc={testimonial.videoSrc}
                        className="w-full h-full object-cover"
                      />

                      <div className="absolute inset-x-4 bottom-4 xl:inset-x-5 xl:bottom-5 2xl:inset-x-6 2xl:bottom-6 flex flex-col gap-1 xl:gap-2 2xl:gap-3 p-4 xl:p-5 2xl:p-6 card rounded backdrop-blur-sm">
                        <div className="flex gap-1.5 mb-1">
                          {Array.from({ length: 5 }).map((_, index) => (
                            <Star
                              key={index}
                              className={cls(
                                "size-5 text-accent",
                                index < testimonial.rating ? "fill-accent" : "fill-transparent"
                              )}
                              strokeWidth={1.5}
                            />
                          ))}
                        </div>

                        <span className="text-2xl font-semibold leading-snug truncate">{testimonial.name}</span>

                        <div className="flex flex-col">
                          <span className="text-base leading-snug truncate">{testimonial.role}</span>
                          <span className="text-base leading-snug truncate">{testimonial.company}</span>
                        </div>
                      </div>
                    </div>

                    {/* Back */}
                    <div className="absolute inset-0 [backface-visibility:hidden] [transform:rotateY(180deg)] card rounded p-6 flex flex-col justify-center items-center text-center overflow-hidden">
                      <div className="flex gap-1.5 mb-4 shrink-0">
                        {Array.from({ length: 5 }).map((_, index) => (
                          <Star
                            key={index}
                            className={cls(
                              "size-5 text-accent",
                              index < testimonial.rating ? "fill-accent" : "fill-transparent"
                            )}
                            strokeWidth={1.5}
                          />
                        ))}
                      </div>
                      <p className="text-base md:text-lg leading-relaxed italic text-foreground overflow-y-auto">"{testimonial.quote}"</p>
                      <span className="mt-4 text-sm font-semibold text-foreground shrink-0">— {testimonial.name}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function TestimonialsSection() {
  return (
    <div data-webild-section="testimonials" id="testimonials">
      <TestimonialsInline />
    </div>
  );
}
